### ISSUE TITLE
"Primary" interface is set to resolve

### ISSUE THREAD

**Issue by nickcmaynard** [sle118/addons-network-manager-fix#3] opened 2024-12-05 20:39 UTC
The addon's working for me, but I have noticed that the end effect is to set the "primary" interface to `resolve`, and leave "secondary" interfaces as `yes`.

This feels counterintuitive, as I'd expect the "primary" interface to be set to `yes` and all secondary interfaces to be set to `resolve`.

To get the effect I want (my primary network announcing the mDNS name, and secondary networks resolving only), I've had to set my *secondary* interface name as the "primary interface" in this addon.

Am I misunderstanding the aim of this addon, or do we have a logic error?  In some ways it doesn't matter a lot, as mDNS reflection generally exists in situations where either IP will work, but I wanted to ask!

**Comment by nickcmaynard** [comment] 2024-12-05 20:43
FWIW, I define "secondary" as secondary physical interfaces, rather than the plethora of veth/docker interfaces that exist in a HomeAssistant OS.

**Comment by sle118** [comment] 2024-12-05 22:06
I wrote the addon mostly to resolve my own issues, which is that the primary interface was spamming the network with requests because the reflectors made them believe there was a collision. This is why the default behavior is to set the primary interface as "resolve" while still providing some provisions to change a different one. 

I have not bothered sniffing the mDNS traffic since I've done the change because it "just worked" for me so this is far as I really went into this and network protocols aren't my strength. 

I originally thought about having an array of interfaces and mDNS modes in the configuration, which would likely have allowed more granular control.

If you want to play around with that, go ahead and clone the repo to the /addons directory of your home assistant instance and experiment with the features you'd like. Make sure you comment out this line, though: 
https://github.com/sle118/addons-network-manager-fix/blob/f26978f579e80606781e51b4920b812412ab62bb/network-manager-fix/config.yaml#L22C1-L22C57
as it will force running the docker container on your locally built addon instead of running from the cloud image. 

When you are satisfied, feel free to submit a PR so the changes can be shared with everyone.

thank you!

**Comment by Stan-Gobien** [comment] 2024-12-06 21:49
I use it as intended.
I have my primary interface as my LAN (where my computer is also on).
I have a secondary interface with my IOT network (all kinds of devices).
For me it's logical that HomeAssisant is only listening on the primary LAN.
The IOT network is where all the mDNS traffic is originating.

**Comment by nickcmaynard** [comment] 2024-12-06 22:22
It sounds like this is one of those situations where different folks want different things.  I'm happy with my setup now - thanks again, @sle118.   It also looks like there's work going on here https://github.com/home-assistant/supervisor/pull/5455 to give us the more flexible approach you suggest, too.

Given that I think those who are using this addon will understand enough about mDNS resolve/announce to configure the appropriate interface to get the effect that they want, I don't think more work here is needed.  Perhaps worth adding a note to the README to outline the behaviour?

**Comment by sle118** [comment] 2024-12-07 22:20
@nickcmaynard how would you phrase it to be intelligible?

**Comment by nickcmaynard** [comment] 2024-12-07 23:30
Fair enough ;-)
Something along the lines of the following:

> This addon sets the mDNS mode on the "Primary" interface (whether autodetected or explicitly configured, e.g. `Supervisor enp1s0`) to `resolve`.
> 
> This means that an mDNS name will *not* be advertised on this interface, and only mDNS resolution will be supported.
>
>  NB. For those running mDNS reflection across VLANs, and using this addon to avoid mDNS name clashes, this may not be the desired behaviour.  In these circumstances, manually configuring the addon's "Primary" interface to point to a secondary interface (say, on an IOT VLAN), will restore mDNS advertisements on Home Assistant's primary interface, and  suppress them on the secondary interface.

**Comment by Stan-Gobien** [comment] 2024-12-08 22:54
I'm running mDNS repeater/reflection on my Firewall (OPNsense).
But I don't understand in what situation it would be better to advertise on the primary (LAN) interface instead of the secondary (IOT VLAN). It may be my lack of understanding, so if you could elaborate?

**Comment by sle118** [comment] 2024-12-09 19:11
Seems like for me, setting the primary interface to resolve works because there's just no other interface on that system (aside from what looks like virtual interfaces from docker addons).  I am starting to wonder if I should dedicate a dedicated network adapter (as opposed to bridging with the host's network adapter) so the iot devices can talk to the home assistant instance without polluting the non-iot network with broadcasts.

@nickcmaynard, do you have some suggestions here? I guess this is too new for me (even if my biggest open source project so far uses mDNS to advertize itself... see https://github.com/sle118/squeezelite-esp32 ) to really understand what would be best.

**Comment by sle118** [comment] 2024-12-12 11:37
I will go ahead and close this now as I believe no further action is needed.

**Closed by sle118** 2024-12-12 11:37 UTC

**Comment by nickcmaynard** [comment] 2024-12-13 10:31
Apologies folks - this has been on my TODO list for a couple of days.

@Stan-Gobien Personal choice in your situation.  AFAICT the choice of advertisement interface influences:
1. Which interface the mDNS advertisement is transmitted on.  In the case of reflection, this is pretty academic as the reflector will duplicate advertisements anyway.
2. Which *IP* the mDNS advertisement contains for the name.  Advertising on interface `enp1s0` which is configured with IP `192.168.1.1` would advertise IP `192.168.1.1`.  That *is* important, as your cross-VLAN routing and forwarding may or may not firewall access from your clients to various IPs.  Entirely down to your network architecture.

@sle118 Hard to know - I'm no expert here either.  My HA sits on my IOT vlan *and* my LAN vlan so it can chat to both halves of my network.  Similarly, I have OPNsense on both VLANs, and explicit routing rules set up there to bridge those VLANs in the ways I want.  I don't use the native linux bridging (IP forward?) as I don't have enough patience to learn the details of iptables/nftables to secure it properly.

@sle118 Sorry to pollute the case with conversation - hope this helps you both.

**Comment by Stan-Gobien** [comment] 2024-12-15 19:28
Thanks for your comment, it helps in understanding.
mDNS is used mostly by the IOT devices, so for me it makes sense that HA advertises it's IOT interface IP address in mDNS packets. 
I also have OPNsense with an intergace in both networks. And I have policies that let traffic pass from my LAN to my IOT network but not the other way.
And myself on my computer in my LAN can access my IOT devices (for example ESPhome) using the mDNS name because the repeater/reflector makes them known in my LAN.

**Comment by ohmantics** [comment] 2025-09-20 07:26
If I understand the situation correctly, I want my primary interface to be "announce" and the secondary to be "resolve". Without that, there is no announcement of "homeassistant.local" anywhere.
